Import Debian changes 1.8.1-1
crun (1.8.1-1) unstable; urgency=medium
.
  * New bugfix upstream release.
  * Provide a lengthier long description.
.
crun (1.8-1) unstable; urgency=medium
.
  * New upstream release.
  * Update debian/watch to point to the GitHub API.
  * Ship the original upstream release, including its signature, instead of
    the DFSG repack. The two binary files were removed in the latest upstream
    release (PR #1126), and libocispec is DFSG-free, even if unused.
  * Rework debian/copyright, to simplify, document previously undocumented
    files (e.g.  libyajl).
  * Bump golang-github-opencontainers-specs-dev Build-Dependency to account
    for required changes there (memory.checkBeforeUpdate).
  * Regenerate a couple of pregenerated files using gperf.
  * Bump debhelper level to 13.
  * Switch buildsystem to autoreconf.
  * Various other misc packaging changes (override -> execute_after,
    d/install, wrap-and-sort -sabt, etc.)
  * Bump Standards-Version to 4.6.2, no further changes needed.
  * Add Reinhard Tartler to uploaders per his request.
.
crun (1.5+dfsg-1) unstable; urgency=medium
.
  * New upstream release. (Closes: #1014306)
    - Includes a fix for CVE-2022-27650 (Closes: #1009881)
    - Remove patch zos.patch, was an upstream backport.
  * Replace invalid field Homepage by field Repository-Browse in upstream
    metadata. Also add Repository and Changelog fields.
  * Install crun.1 from the installed path in /usr/share/man, rather than the
    source tree, silencing a dh_missing warning.
  * Bump build-dep of golang-github-opencontainers-specs-dev to
    >= v1.0.2.102.ga8106e9, which includes commit 2792412 for cpu.idle.
  * Bump Standards-Version to 4.6.1, no changes needed.
  * Add myself to Uploaders.
.
crun (0.17+dfsg-1.1) unstable; urgency=medium
.
  * Non-maintainer upload.
  * Bug fix: "FTBFS: undefined reference to
    `gen_runtime_spec_schema_config_zos", thanks to Lucas Nussbaum
    (Closes: #997225).
.
crun (0.17+dfsg-1) unstable; urgency=medium
.
  * New upstream release.
.
crun (0.16+dfsg-1) unstable; urgency=medium
.
  * New upstream release.
.
crun (0.15.1+dfsg-1) unstable; urgency=medium
.
  * New upstream release.
.
crun (0.15+dfsg-1) unstable; urgency=medium
.
  * New upstream release.
  * rules: don't install .la file.
.
crun (0.14.1+dfsg-1) unstable; urgency=medium
.
  * New upstream release.
.
crun (0.13+dfsg-1) unstable; urgency=medium
.
  * New upstream release.
  * Rules-Requires-Root: no.
.
crun (0.12.2.1+dfsg-1) unstable; urgency=medium
.
  * New upstream release.
.
crun (0.12.1+dfsg-1) unstable; urgency=medium
.
  * New upstream release.
.
crun (0.12+dfsg-1) unstable; urgency=medium
.
  * New upstream release.
  * Standards-Version: 4.5.0.
.
crun (0.11+dfsg-1) unstable; urgency=medium
.
  * New upstream release.
.
crun (0.10.6+dfsg-1) unstable; urgency=medium
.
  * New upstream release.
.
crun (0.10.5+dfsg-1) unstable; urgency=medium
.
  * Initial release (Closes: #944087).